### ISSUE TITLE
UnicodeEncodeError: 'cp949' codec can't encode character '\ufffd'

### ISSUE THREAD

**Issue by kim-do-hyeon** [kim-do-hyeon/Volaltility-gui#5]
### UnicodeEncodeError: 'cp949' codec can't encode character '\ufffd' in position 39: illegal multibyte sequence

![image](https://user-images.githubusercontent.com/21982942/76850898-aa973300-688b-11ea-8b57-6c34f053c92b.png)

**Comment by kim-do-hyeon** [comment]
[error_log.txt](https://github.com/kim-do-hyeon/volatility-gui/files/5297302/error_log.txt)

G:\Vol\Volaltility-gui\auto>python auto.py
windows.cmdline
windows.dlllist00               Scanning primary2 using PdbSignatureScanner
windows.filescan0               Scanning primary2 using PdbSignatureScanner
**Traceback (most recent call last):anning primary2 using PdbSignatureScanner
  File "G:\Vol\Volaltility-gui\auto/volatility3/vol.py", line 10, in <module>
    volatility.cli.main()
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\__init__.py", line 515, in main
    CommandLine().run()
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\text_renderer.py", line 181, in render
    grid.populate(visitor, outfd)
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\framework\renderers\__init__.py", line 218, in populate
    accumulator = function(treenode, accumulator)
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\text_renderer.py", line 176, in visitor
    accumulator.write("{}".format("\t".join(line)))
UnicodeEncodeError: 'cp949' codec can't encode character '\u0202' in position 10: illegal multibyte sequence**
windows.handles
windows.info 0.00               Scanning primary2 using PdbSignatureScanner
windows.malfind00               Scanning primary2 using PdbSignatureScanner
windows.modscan00               Scanning primary2 using PdbSignatureScanner
**Traceback (most recent call last):anning primary2 using PdbSignatureScanner
  File "G:\Vol\Volaltility-gui\auto/volatility3/vol.py", line 10, in <module>
    volatility.cli.main()
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\__init__.py", line 515, in main
    CommandLine().run()
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\text_renderer.py", line 181, in render
    grid.populate(visitor, outfd)
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\framework\renderers\__init__.py", line 218, in populate
    accumulator = function(treenode, accumulator)
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\text_renderer.py", line 176, in visitor
    accumulator.write("{}".format("\t".join(line)))
UnicodeEncodeError: 'cp949' codec can't encode character '\ue110' in position 37: illegal multibyte sequence**
windows.modules
windows.mutantscan              Scanning primary2 using PdbSignatureScanner
windows.poolscanner             Scanning primary2 using PdbSignatureScanner
**Traceback (most recent call last):anning primary2 using PdbSignatureScanner
  File "G:\Vol\Volaltility-gui\auto/volatility3/vol.py", line 10, in <module>
    volatility.cli.main()
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\__init__.py", line 515, in main
    CommandLine().run()
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\text_renderer.py", line 181, in render
    grid.populate(visitor, outfd)
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\framework\renderers\__init__.py", line 218, in populate
    accumulator = function(treenode, accumulator)
  File "G:\Vol\Volaltility-gui\auto\volatility3\volatility\cli\text_renderer.py", line 176, in visitor
    accumulator.write("{}".format("\t".join(line)))
UnicodeEncodeError: 'cp949' codec can't encode character '\u0202' in position 48: illegal multibyte sequence**
windows.pslist
windows.psscan.00               Scanning primary2 using PdbSignatureScanner
windows.pstree.00               Scanning primary2 using PdbSignatureScanner
windows.registry.certificates   Scanning primary2 using PdbSignatureScanner
windows.registry.hivelist       Scanning primary2 using PdbSignatureScanner
windows.registry.hivescan       Scanning primary2 using PdbSignatureScanner
windows.registry.printkey       Scanning primary2 using PdbSignatureScanner
windows.registry.userassist     Scanning primary2 using PdbSignatureScanner
windows.ssdt 0.00               Scanning primary2 using PdbSignatureScanner
windows.statistics              Scanning primary2 using PdbSignatureScanner
windows.strings92               Reading memory
usage: volatility windows.strings.Strings [-h] --strings-file STRINGS_FILE
volatility windows.strings.Strings: error: the following arguments are required: --strings-file
windows.symlinkscan
windows.vadinfo00               Scanning primary2 using PdbSignatureScanner
windows.verinfo00               Scanning primary2 using PdbSignatureScanner
Successs:    0.00               Scanning primary2 using PdbSignatureScanner
